config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root to: 'home#index'

  get 'home/index'

  get 'api/uplink_stations'
  get 'api/satellite_vehicles'
  get 'api/update_events'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/satellite_vehicle.rb
class SatelliteVehicle < ApplicationRecord
  has_many :update_events, -> { order(:created_at) }

  def iod_age
    Time.current - last_iod_update
  end

  def last_iod_update
    update_events.last.created_at
  end

  def css_class
    if iod_age > 3600
      'stale-3600'
    elsif iod_age > 1800
      'stale-1800'
    elsif iod_age > 700
      'stale-700'
    end
  end
end

app/models/update_event.rb
class UpdateEvent < ApplicationRecord
  belongs_to :satellite_vehicle
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  UPLINK_STATIONS = [
    { coord: [-17.5386449, -149.6194316], name: "Papeete" },
    { coord: [  5.1648168,  -52.6596651], name: "Kourou"  },
    { coord: [ 78.2404686,   15.7969334], name: "Svalbard"},
    { coord: [-20.9115274,   55.5131576], name: "Réunion" },
    { coord: [-22.2642742,  166.4098473], name: "Nouméa"  },
  ].freeze

  def uplink_stations
    render json: UPLINK_STATIONS
  end

  def satellite_vehicles
    satellite_vehicles = SatelliteVehicle
      .where(system: params[:system])
      .where.not(iod: nil)
      .where.not(latitude: nil)
      .where.not(longitude: nil)
      .order(name: :asc)
      .includes(:update_events)

    satellite_vehicles_json = satellite_vehicles.map do |satellite_vehicle|
      {
        name:       satellite_vehicle.name,
        coord:      [satellite_vehicle.latitude, satellite_vehicle.longitude],
        iod:        satellite_vehicle.iod,
        iod_age:    satellite_vehicle.iod_age.to_i,
        updated_at: satellite_vehicle.updated_at,
      }
    end

    render json: satellite_vehicles_json
  end

  def update_events
    last_hours = params[:last_hours].try(:to_i) || 2

    update_events = UpdateEvent
      .joins(:satellite_vehicle)
      .includes(:satellite_vehicle)
      .where(satellite_vehicles: { system: params[:system] })
      .where(created_at: last_hours.hours.ago..)

    events_json = update_events.map do |event|
      {
        c: [ event.latitude, event.longitude ],
        sv: event.satellite_vehicle.name,
        iod: event.iod,
        at: event.created_at,
      }
    end

    render json: events_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  DEFAULT_SYSTEM = :galileo
  SYSTEMS = [
    :galileo,
    :beidou,
    :glonass,
    :gps,
  ]

  def index
    @systems = SYSTEMS
    @system = params[:system]
    @last_hours = params[:last_hours]

    if !@system.present?
      redirect_to home_index_path(system: DEFAULT_SYSTEM)
    end

    @svs = SatelliteVehicle
      .where(system: @system)
      .where.not(iod: nil)
      .order(name: :asc)
      .includes(:update_events)
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Location of IOD updated on <%= @system %> GNSS</h1>

Last
<% (1..24).each do |hour| %>
  <% if @last_hours == hour.to_s %>
    <b><%= @last_hours %></b>
  <% else %>
    <%= link_to hour, home_index_path(system: @system, last_hours: hour) -%>
  <% end %>
<% end %>
 hours. <%= link_to "All data", home_index_path(system: @system, last_hours: 10_000_000) -%>.<br/>

GNSS system: <% @systems.each do |system| %>
  <% if @system == system.to_s %>
    <b><%= @system %></b>
  <% else %>
    <%= link_to system, home_index_path(system: system, last_hours: @last_hours) -%>
  <% end %>
<% end %>
<br/>
<br/>

<div id="mapid"></div>

<script>
  var mymap = L.map('mapid').setView([0.0, 0.0], 2);
  L.control.scale().addTo(mymap);

  L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiY2h0aXR1eCIsImEiOiJja2kzNjZ2Z20wYzlwMzBxczUzOHY1ZDZkIn0.6VWek7i1QwOwRbpI23Ynjw', {
  	maxZoom: 5,
  	attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
  		'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'GNSS data from <a href="https://galmon.eu/">galmon.eu</a>, ' +
  		'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
  	id: 'mapbox/streets-v11',
  	tileSize: 512,
  	zoomOffset: -1
  }).addTo(mymap);

  function loadUpdateEvents() {
    var update_events = JSON.parse(this.response);

    for (const update_event of update_events) {
      L.circle(update_event.c, 500, {
        color: '#5f005f',
        fillColor: '#5f005f',
        fillOpacity: 0.5
      }).addTo(mymap).bindPopup(update_event.sv+" received IOD "+update_event.iod+" on "+update_event.at);
    }
  }

  function loadSatelliteVehicles () {
    var satellite_vehicles = JSON.parse(this.response);

    for (const satellite_vehicle of satellite_vehicles) {
      color = '#008000';
      if(satellite_vehicle.iod_age > 3600) {
        color = 'red';
      } else if (satellite_vehicle.iod_age > 1800) {
        color = '#ff6a00';
      } else if (satellite_vehicle.iod_age > 700) {
        color = '#cec700';
      }

      L.circle(satellite_vehicle.coord, 100000, {
        color: color,
        fillColor: color,
        fillOpacity: 0.5
      }).addTo(mymap).bindPopup("SV "+satellite_vehicle.name+" has IOD "+satellite_vehicle.iod+", "+satellite_vehicle.iod_age+" seconds old");
    }
  }

  function loadUplinkStations () {
    var uplink_stations = JSON.parse(this.response);

    for (const station of uplink_stations) {
      L.marker(station.coord, 500, {
      	color: 'red',
      	fillColor: '#e4213e',
      	fillOpacity: 0.5
      }).addTo(mymap).bindPopup(station.name+" uplink station");
      L.circle(station.coord, 7000000, {
        color: 'none',
        fillColor: '#1b00ff',
        fillOpacity: 0.1
      }).addTo(mymap)
    }
  }

  var uplink_station_xhr = new XMLHttpRequest();
  uplink_station_xhr.addEventListener('load', loadUplinkStations);
  uplink_station_xhr.open('GET', '<%= api_uplink_stations_path(system: @system).html_safe %>');
  uplink_station_xhr.send();

  var satellite_vehicles_xhr = new XMLHttpRequest();
  satellite_vehicles_xhr.addEventListener('load', loadSatelliteVehicles);
  satellite_vehicles_xhr.open('GET', '<%= api_satellite_vehicles_path(system: @system).html_safe %>');
  satellite_vehicles_xhr.send();

  var update_events_xhr = new XMLHttpRequest();
  update_events_xhr.addEventListener('load', loadUpdateEvents);
  update_events_xhr.open('GET', '<%= api_update_events_path(system: @system, last_hours: @last_hours).html_safe %>');
  update_events_xhr.send();
</script>
<table>
  <thead>
    <tr><th>Name</th><th>Lat/long</th><th>IOD</th><th>IOD age</th><th>Last update</th></tr>
  </thead>
  <tbody>
    <% @svs.each do |sv| %>
      <tr class="<%= sv.css_class %>">
        <td><%= sv.name %></td>
        <td><%= sv.latitude %>, <%= sv.longitude %></td>
        <td><%= sv.iod %></td>
        <td><%= time_ago_in_words(sv.last_iod_update, include_seconds: true) %></td>
        <td><%= time_ago_in_words(sv.updated_at, include_seconds: true) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GNSS IOD Watcher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.png'), rel: 'apple-touch-icon', type: 'image/png' %>
    <%= favicon_link_tag asset_path('favicon.png'), type: 'image/png' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
      integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
      crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
      integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
      crossorigin=""></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>